{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-quality-filter
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas
    - numpy
    - qiime2 {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2templates >={{ q2templates }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_quality_filter
    - qiime2.plugins.quality_filter

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
